import type { DashboardStats, Holding, Transaction, AIRecommendation, PortfolioDataPoint, ActivityItem } from '../types/index.js'

export const portfolioHistory: PortfolioDataPoint[] = [
  { date: 'Jun 23', value: 178420, benchmark: 175000 },
  { date: 'Jul 23', value: 185340, benchmark: 178200 },
  { date: 'Aug 23', value: 179820, benchmark: 176800 },
  { date: 'Sep 23', value: 192150, benchmark: 181400 },
  { date: 'Oct 23', value: 205430, benchmark: 188900 },
  { date: 'Nov 23', value: 218760, benchmark: 195300 },
  { date: 'Dec 23', value: 225890, benchmark: 200100 },
  { date: 'Jan 24', value: 219340, benchmark: 197500 },
  { date: 'Feb 24', value: 231670, benchmark: 203800 },
  { date: 'Mar 24', value: 238910, benchmark: 208600 },
  { date: 'Apr 24', value: 235420, benchmark: 206200 },
  { date: 'May 24', value: 247832, benchmark: 212400 },
]

export const holdings: Holding[] = [
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    assetType: 'STOCK',
    shares: 45,
    avgPrice: 152.3,
    currentPrice: 189.84,
    value: 8542.8,
    allocation: 34.4,
    change24h: 2.34,
    changePercent24h: 1.25,
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corp.',
    assetType: 'STOCK',
    shares: 12,
    avgPrice: 420.5,
    currentPrice: 875.4,
    value: 10504.8,
    allocation: 42.3,
    change24h: 18.7,
    changePercent24h: 2.18,
  },
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    assetType: 'CRYPTO',
    shares: 0.85,
    avgPrice: 38200,
    currentPrice: 67840,
    value: 57664,
    allocation: 23.2,
    change24h: 1240,
    changePercent24h: 1.86,
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    assetType: 'CRYPTO',
    shares: 8.2,
    avgPrice: 2100,
    currentPrice: 3580,
    value: 29356,
    allocation: 11.8,
    change24h: -42,
    changePercent24h: -1.16,
  },
  {
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF',
    assetType: 'ETF',
    shares: 30,
    avgPrice: 445.2,
    currentPrice: 524.8,
    value: 15744,
    allocation: 6.3,
    change24h: 3.2,
    changePercent24h: 0.61,
  },
  {
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    assetType: 'STOCK',
    shares: 20,
    avgPrice: 198.4,
    currentPrice: 174.9,
    value: 3498,
    allocation: 1.4,
    change24h: -5.4,
    changePercent24h: -2.99,
  },
  {
    symbol: 'AGG',
    name: 'US Aggregate Bond ETF',
    assetType: 'BOND',
    shares: 85,
    avgPrice: 95.2,
    currentPrice: 96.8,
    value: 8228,
    allocation: 3.3,
    change24h: 0.12,
    changePercent24h: 0.12,
  },
]

export const transactions: Transaction[] = [
  {
    id: 'tx-001',
    type: 'BUY',
    symbol: 'NVDA',
    name: 'NVIDIA Corp.',
    shares: 3,
    price: 875.4,
    total: 2626.2,
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-002',
    type: 'SELL',
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    shares: 5,
    price: 174.9,
    total: 874.5,
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-003',
    type: 'BUY',
    symbol: 'BTC',
    name: 'Bitcoin',
    shares: 0.05,
    price: 67840,
    total: 3392,
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-004',
    type: 'BUY',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    shares: 10,
    price: 189.84,
    total: 1898.4,
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-005',
    type: 'SELL',
    symbol: 'ETH',
    name: 'Ethereum',
    shares: 1.5,
    price: 3580,
    total: 5370,
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-006',
    type: 'BUY',
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF',
    shares: 5,
    price: 524.8,
    total: 2624,
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-007',
    type: 'BUY',
    symbol: 'AGG',
    name: 'US Aggregate Bond ETF',
    shares: 20,
    price: 96.8,
    total: 1936,
    status: 'PENDING',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
]

export const recommendations: AIRecommendation[] = [
  {
    id: 'rec-001',
    title: 'Increase NVDA exposure',
    description: 'NVIDIA shows strong momentum driven by AI chip demand. Technical indicators suggest continued upside.',
    type: 'BUY',
    symbol: 'NVDA',
    confidence: 87,
    impact: 'HIGH',
    reasoning: 'AI infrastructure spending is accelerating. NVDA P/E relative to growth remains attractive. Institutional accumulation detected.',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rec-002',
    title: 'Rebalance crypto allocation',
    description: 'Your crypto exposure (35.1%) exceeds the recommended 25% for your risk profile. Consider trimming.',
    type: 'REBALANCE',
    confidence: 79,
    impact: 'MEDIUM',
    reasoning: 'Volatility-adjusted returns suggest over-exposure. Rebalancing to 25% would reduce portfolio VaR by ~12%.',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rec-003',
    title: 'Reduce TSLA position',
    description: 'Tesla shows bearish RSI divergence and declining delivery growth. Risk/reward unfavorable at current levels.',
    type: 'SELL',
    symbol: 'TSLA',
    confidence: 81,
    impact: 'MEDIUM',
    reasoning: 'EV market saturation concerns, margin compression, and CEO distraction factors weigh on near-term outlook.',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rec-004',
    title: 'BTC accumulation zone',
    description: 'Bitcoin is in a historically strong accumulation zone post-halving. On-chain metrics are bullish.',
    type: 'BUY',
    symbol: 'BTC',
    confidence: 73,
    impact: 'HIGH',
    reasoning: 'Post-halving supply shock combined with ETF demand surge. Historical patterns suggest 6-12 month bull cycle.',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rec-005',
    title: 'Add inflation hedge',
    description: 'Macro indicators suggest inflationary pressures. Consider adding gold ETF (GLD) for portfolio protection.',
    type: 'BUY',
    symbol: 'GLD',
    confidence: 64,
    impact: 'LOW',
    reasoning: 'CPI trends, Fed policy uncertainty, and geopolitical risks favor defensive positioning in real assets.',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const activity: ActivityItem[] = [
  {
    id: 'act-001',
    type: 'TRADE',
    title: 'Bought NVDA',
    description: 'Purchased 3 shares at $875.40',
    amount: 2626.2,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-002',
    type: 'AI_ALERT',
    title: 'AI Alert: TSLA Overbought Signal',
    description: 'RSI divergence detected on 4h chart',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-003',
    type: 'TRADE',
    title: 'Sold TSLA',
    description: 'Sold 5 shares at $174.90',
    amount: -874.5,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-004',
    type: 'DIVIDEND',
    title: 'Dividend Received',
    description: 'SPY quarterly dividend payment',
    amount: 47.3,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-005',
    type: 'REBALANCE',
    title: 'Portfolio Rebalanced',
    description: 'AI-suggested rebalancing executed',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-006',
    type: 'AI_ALERT',
    title: 'AI Alert: BTC Bull Pattern',
    description: 'Post-halving accumulation zone detected',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const assetAllocation = [
  { name: 'Stocks', value: 44.7, color: '#6366f1' },
  { name: 'Crypto', value: 35.1, color: '#a855f7' },
  { name: 'ETFs', value: 16.9, color: '#22d3ee' },
  { name: 'Bonds', value: 3.3, color: '#10b981' },
]

export const getDashboardStats = (): DashboardStats => ({
  portfolio: {
    totalValue: 247832.54,
    monthlyGain: 12398.54,
    monthlyGainPercent: 12.4,
    riskScore: 72,
    aiSuggestions: 5,
  },
  holdings,
  transactions,
  recommendations,
  portfolioHistory,
  activity,
})
